src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Table;
use Doctrine\ORM\Mapping\UniqueConstraint;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 * @UniqueEntity("name")
 * @Table(
 *     name="`user`",
 *     uniqueConstraints={
 *         @UniqueConstraint(name="email_unique",columns={"email"}),
 *         @UniqueConstraint(name="user_name_unique",columns={"name"})
 *     }
 * )
 */
class User implements UserInterface, EquatableInterface
{

    const ROLE_USER      =  0;
    const ROLE_ORACLE    =  2;
    const ROLE_CROW      =  3;
    const ROLE_ADMIN     =  4;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=190)
     */
    private $email;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $pass;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validated;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\UserPendingValidation", mappedBy="user", cascade={"persist", "remove"})
     */
    private $pendingValidation;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Citizen", mappedBy="user")
     */
    private $citizens;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AdminBan", mappedBy="user")
     */
    private $bannings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\FoundRolePlayText", mappedBy="user")
     */
    private $foundTexts;

    /**
     * @ORM\Column(type="integer")
     */
    private $soulPoints = 0;
    
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picto", mappedBy="user")
     */
    private $pictos;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Award", mappedBy="user")
     */
    private $awards;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $externalId = '';

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Avatar", cascade={"persist", "remove"})
     */
    private $avatar;

    /**
     * @ORM\Column(type="boolean")
     */
    private $preferSmallAvatars = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postAsDefault;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $forumTitle;

    /**
     * This field matches to the filename of the picto
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $forumIcon;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $language = "de";

    /**
     * @ORM\Column(type="smallint")
     */
    private $rightsElevation = 0;

    /**
     * @ORM\OneToMany(targetEntity=CitizenRankingProxy::class, mappedBy="user", orphanRemoval=true)
     */
    private $pastLifes;

    /**
     * @ORM\Column(type="integer")
     */
    private $heroDaysSpent = 0;

    public function __construct()
    {
        $this->citizens = new ArrayCollection();
        $this->foundTexts = new ArrayCollection();
        $this->pictos = new ArrayCollection();
        $this->bannings = new ArrayCollection();
        $this->pastLifes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getForumIcon(): ?string {
        return $this->forumIcon;
    }

    public function setForumIcon(string $value): self {
        $this->forumIcon = $value;

        return $this;
    }

    public function getForumTitle(): ?string {
        return $this->forumTitle;
    }

    public function setForumTitle(string $value): self {
        $this->forumTitle = $value;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSalt( ): string {
        return 'user_salt_myhordes_ffee45';
    }

    /**
     * @return Collection|AdminBan[]
     */
    public function getBannings(): Collection
    {
        return $this->bannings;
    }

    public function getValidated(): ?bool
    {
        return $this->validated;
    }

    public function setValidated(bool $validated): self
    {
        $this->validated = $validated;

        return $this;
    }

    public function getPendingValidation(): ?UserPendingValidation
    {
        return $this->pendingValidation;
    }

    public function setPendingValidation(?UserPendingValidation $pendingValidation): self
    {
        $this->pendingValidation = $pendingValidation;

        // set (or unset) the owning side of the relation if necessary
        $newUser = null === $pendingValidation ? null : $this;
        if ($pendingValidation && $pendingValidation->getUser() !== $newUser) {
            $pendingValidation->setUser($newUser);
        }

        return $this;
    }

    /**
     * @inheritDoc
     */
    public function getRoles()
    {
        $roles = [];
        if ($this->pass === null) return $roles;
        if ($this->rightsElevation >= 4) $roles[] = 'ROLE_ADMIN';
        if ($this->rightsElevation >= 3) $roles[] = 'ROLE_CROW';
        if (strstr($this->email, "@localhost") === "@localhost") $roles[] = 'ROLE_DUMMY';        
        if ($this->validated) $roles[] = 'ROLE_USER';
        else $roles[] = 'ROLE_REGISTERED';
        if ($this->getIsBanned()) $roles[] = 'ROLE_BANNED';        
        return $roles;
    }

    /**
     * @inheritDoc
     */
    public function getPassword()
    {
        return $this->pass;
    }

    public function setPassword(?string $pass): self {
        $this->pass = $pass;
        return $this;
    }

    /**
     * @inheritDoc
     */
    public function eraseCredentials() {}

    /**
     * @inheritDoc
     */
    public function isEqualTo(UserInterface $user) {
        $b1 = $this->getPassword() !== null && $user->getPassword() !== null &&
            $this->getUsername() === $user->getUsername() &&
            $this->getPassword() === $user->getPassword() &&
            $this->getRoles() === $user->getRoles();
        if ($user instanceof User) {
            return $b1 &&
                $this->getRightsElevation() === $user->getRightsElevation();
        } else return $b1;
    }

    public function getIsBanned(): bool {
        foreach ($this->getBannings() as $b)
            if ($b->getActive())
                return true;
        return false;
    }

    public function getLongestActiveBan(): ?AdminBan {
        $ban = null;
        foreach ($this->getBannings() as $b){
            if ($b->getActive()) {
                if (!isset($ban)) {
                    $ban = $b;                       
                }
                else if ($b->getBanEnd() > $ban->getBanEnd())
                    $ban = $b;     
            }
        }            
        if (isset($ban))
            return $ban;
        return null;
    }

    /**
     * @return Collection|AdminBan[]
     */
    public function getActiveBans(): Collection {
        $bans = $this->getBannings();
        foreach ($bans as $ban){
                if (!($ban->getActive()))
                    $bans->remove($ban->getId());  
            }            
        return $bans;
    }

    public function getActiveCitizen(): ?Citizen {
        foreach ($this->getCitizens() as $c)
            if ($c->getActive())
                return $c;
        return null;
    }

    public function getAliveCitizen(): ?Citizen {
        foreach ($this->getCitizens() as $c)
            if ($c->getAlive())
                return $c;
        return null;
    }

    /**
     * @return Collection|Citizen[]
     */
    public function getCitizens(): Collection
    {
        return $this->citizens;
    }

    public function addCitizen(Citizen $citizen): self
    {
        if (!$this->citizens->contains($citizen)) {
            $this->citizens[] = $citizen;
            $citizen->setUser($this);
        }

        return $this;
    }

    public function removeCitizen(Citizen $citizen): self
    {
        if ($this->citizens->contains($citizen)) {
            $this->citizens->removeElement($citizen);
            // set the owning side to null (unless already changed)
            if ($citizen->getUser() === $this) {
                $citizen->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|RolePlayText[]
     */
    public function getFoundTexts(): Collection
    {
        return $this->foundTexts;
    }

    public function addFoundText(RolePlayText $foundText): self
    {
        if (!$this->foundTexts->contains($foundText)) {
            $this->foundTexts[] = $foundText;
        }

        return $this;
    }

    public function removeFoundText(RolePlayText $foundText): self
    {
        if ($this->foundTexts->contains($foundText)) {
            $this->foundTexts->removeElement($foundText);
        }

        return $this;
    }

    public function getSoulPoints(): ?int
    {
        return $this->soulPoints;
    }

    public function setSoulPoints(int $soulPoints): self
    {
        $this->soulPoints = $soulPoints;

        return $this;
    }

    public function addSoulPoints(int $soulPoints): self
    {
        $this->soulPoints += $soulPoints;

        return $this;
    }


    public function getExternalId(): ?string
    {

templates/ajax/soul/death.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block ajax %}
    {# @var citizen \App\Entity\CitizenRankingProxy #}

    <div class="row">
        <div class="cell ro-2 rw-8 ro-lg-1 rw-lg-10 ro-md-0 rw-md-12">
            <div class="death_header">
                <div>{{ 'Herzlichen Glückwunsch, du bist TOT!'|trans({},'game') }}</div>
                <div>{{ citizen.cod.label|trans({},'game') }}</div>
            </div>
            <div class="death_footer">
                {{ 'Du hast %sp% Seelenpunkte gewonnen!'|trans({'%sp%':sp},'game') }}
            </div>

            <br />

            <div class="row">
                <div class="cell rw-6 rw-sm-12">
                    <img class="fit" alt="" src="{{ asset('build/images/death/' ~ citizen.cod.icon ~ '.jpg') }}" />
                    <div class="small-note">{{ citizen.cod.description|trans({},'game') }}</div>
                    <button x-ajax-href="{{ path('game_newspaper') }}" {% if not gazette %}disabled{% endif %}>{{ 'Die letzte Zeitung lesen'|trans({},'game') }}</button>
                </div>
                <div class="cell rw-6 rw-sm-12">
                    <div class="death_list">
                        <b>{{ 'Du hast folgende Auszeichnungen verliehen bekommen:'|trans({},'game')  }}</b>
                        <ul>
                        {% for picto in pictos %}
                            <li {% if picto.prototype.rare %}class="rare"{% endif %}>
                                <div>
                                    <img alt="" src="{{  asset('build/images/pictos/' ~ picto.prototype.icon ~ '.gif') }}" />
                                </div>
                                {{picto.prototype.label|trans({}, 'game')}} <span class="count">+ {{picto.count}}</span>
                                <div class="tooltip">
                                    <h1>{{ picto.prototype.label|trans({}, 'game') }}</h1>
                                    {{ picto.prototype.description|trans({}, 'game')}}
                                </div>
                            </li>
                        {% endfor %}
                        </ul>
                        {% if denied_pictos|length > 0 %}
                            <b>{{ 'Wenn du eine zusätzliche Nacht geblieben wärst, hättest du auch die folgenden Preise gewinnen können:'|trans({},'game')  }}</b>
                            <ul>
                            {% for picto in denied_pictos %}
                                <li {% if picto.prototype.rare %}class="rare"{% endif %}>
                                    <div>
                                        <img src="{{  asset('build/images/pictos/' ~ picto.prototype.icon ~ '.gif') }}" />
                                    </div>
                                    {{picto.prototype.label|trans({}, 'game')}} <span class="count">+ {{picto.count}}</span>
                                    <div class="tooltip">
                                        <h1>{{ picto.prototype.label|trans({}, 'game') }}</h1>
                                        {{ picto.prototype.description|trans({}, 'game')}}</em>
                                    </div>
                                </li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="padded cell rw-12">
                    <h5>{{ 'Begrüße den Tod wie es sich gehört...'|trans({},'game') }}</h5>
                </div>
                <div class="padded cell rw-12">
                    <div class="note">
                        <b>{{ 'Der Tod in "MyHordes" ist nicht weiter schlimm!'|trans({},'game') }}</b>
                        {{ 'Du kannst in einer neuen Stadt wiedergeboren werden und das so oft wie du möchtest. Sei erfinderisch, probiere verschiedene Optionen aus und finde deinen eigenen Spielstil!'|trans({},'game') }}
                    </div>
                </div>
                <div class="rebirth padded rw-12 cell row">
                    {% if citizen.cod.ref != constant('App\\Entity\\CauseOfDeath::Poison') and citizen.cod.ref != constant('App\\Entity\\CauseOfDeath::GhulEaten')  %}
                    <div class="cell rw-4 rebirth_label">
                        <label for="last_words">{{'Deine letzten Worte:'|trans({}, 'game')}}</label>
                    </div>
                    <div class="cell rw-8">
                        <input type="text" name="last_words" id="last_words" placeholder="{{ '' }}" />
                    </div>
                    {% endif %}
                    <div class="cell rw-12 rebirth_btn">
                        <button id="rebirth_btn">{{ 'Wiedergeboren werden'|trans({},'game') }}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        document.getElementById('rebirth_btn').addEventListener('click', function() {
            if (confirm('{{ 'Bist du sicher?'|trans({},'global') }}')) {
                var lastWords = "";
                if(document.getElementById("last_words") !== null)
                    lastWords = document.getElementById("last_words").value;
                
                $.ajax.easySend( '{{ path('api_unsubscribe') }}', {lastwords: lastWords},
                    function () {
                        $.ajax.load(null, '{{ path('initial_landing') }}', true);
                    } );
            }
        });
    </script>
{% endblock %}

templates/ajax/soul/me.html.twig
{% extends "ajax/soul/shell.html.twig" %}
{% block soul_content %}
    <div class="row">
        <div class="cell rw-12 center skills">
            <div class="bar">
                <div class="progresstext"><span class="text">{{progress}}%</span></div>
                <div class="progressbar left">
                    <img src="{{ asset('build/images/soul/heroUp_bar.gif') }}" style="width : {{progress}}%;" />
                </div>
            </div>
            <div class="rp-context">
                {{'Letzter freigeschalteter Heldenvorteil:'|trans({}, 'game')}}
                <strong>{% if latestSkill is not null %}
                    <img src="{{asset('build/images/heroskill/' ~ latestSkill.icon ~ '.gif')}}" alt="">
                    {{latestSkill.title|trans({}, 'game')}}
                {% else %}
                    {{'Niemand'|trans({}, 'game')}}
                {% endif %}</strong>
            </div>
            <div>
                <span class="small link" x-ajax-href="{{ path('soul_heroskill') }}">{{'Alle freigeschalteten Vorteile anzeigen'|trans({}, 'game')}}</span>
            </div>
        </div>
        <div class="cell rw-5 rw-sm-12 distinctions">
            <div class="distinctions-head center">
                {{ 'Statistiken'|trans({}, 'global') }}
            </div>
            <div class="distinctions-list center">
                <div class="overall">
                    {{ '%points% Punkte'|trans({'%points%':points}, 'global') }}
                </div>
                {% if pictos|length == 0 %}
                <div class="list empty">
                    {{ 'Dieser Spieler hat bisher noch keine Preise gewonnen...'|trans({}, 'global') }}
                </div>
                {% else %}
                <div class="list">
                    {% for picto in pictos %}
                        <div class="picto{% if picto.rare %} rare{% endif %}">
                            <img src="{{  asset('build/images/pictos/' ~ picto.icon ~ '.gif') }}" /><br />
                            <div class="counter">
                            {% for number in picto.c|split('') %}<span class="count" title="{{number}}">{{number}}</span>{% endfor %}
                            </div>
                            <div class="tooltip">
                                <h1>{{ picto.label|trans({}, 'game') }}</h1>
                                {{ picto.description|trans({}, 'game')}}</em>
                            </div>
                        </div>
                        {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="distinctions-foot">
                &nbsp;
            </div>
        </div>
        <div class="cell padded rw-7 rw-sm-12">

            <div class="score"><img src="{{ asset('build/images/soul/small_score.gif') }}" alt="" /> {{ 'Seelenpunktzahl'|trans({}, 'global') }} : <strong>{{ '%points% Punkte'|trans({'%points%': app.user.soulPoints}, 'global') }}</strong></div>

            {% for incarnation in app.user.pastLifes %}
                {# @var incarnation \App\Entity\CitizenRankingProxy #}
                {% if incarnation.end is null %}
                    <div class="current">
                        <em>{{'Aktuelles Leben'|trans({}, 'global')}} : </em><br /><strong><img src="{{ asset('build/images/soul/r_explor.gif') }}" alt="" /> {{ incarnation.town.name }}</strong> ({{ 'Tag %day%'|trans({ '%day%':incarnation.town.days }, 'game') }})
                    </div>
                {% endif %}
            {% endfor %}

            <div class="town-history">
                <div class="row header">
                    <div class="cell padded rw-2 center">
                        {{'Saison'|trans({}, 'global')}}
                    </div>
                    <div class="cell padded rw-6 center">
                        {{'Stadt'|trans({}, 'game')}}
                    </div>
                    <div class="cell padded rw-2 center">
                        {{'Tage'|trans({}, 'global')}}
                    </div>
                    <div class="cell padded rw-2 center">
                        {{'Punkte'|trans({}, 'global')}}
                    </div>
                </div>
                <div class="town-container">
                    {#@var incarnation CitizenRankingProxy #}
                    {% for incarnation in app.user.pastLifes|filter(incarnation => incarnation.end is not null)|sort((a,b) => a.day < b.day) %}
                        <div class="row{% if incarnation.town.type.name == 'panda' %} hardcore{% endif %}">
                            <div class="cell padded rw-2 center">
                                {% if incarnation.town.season is null %}
                                    --
                                {% else %}
                                    {{ incarnation.town.season }}
                                {% endif %}
                            </div>
                            <div class="cell padded rw-6 center town-name">
                                <div x-ajax-href="{{ path('soul_view_town', {id: incarnation.town.id}) }}">{% if incarnation.town.type.name == 'panda' %}<img src="{{ asset('build/images/soul/r_cannib.gif') }}" alt="" /> {% endif %}{{ incarnation.town.name }}</div>
                                <div x-town-id="{{ incarnation.id }}" class="comment"><em>{% if not incarnation.comment is empty %}{{incarnation.comment}}{% else %}<span class="add-comment">{{'Einen Kommentar hinzufügen'|trans({}, 'soul')}}</span>{% endif %}</em></div>
                            </div>
                            <div class="cell padded rw-2 center town-days bold">
                                {{ incarnation.day }}
                                {% if incarnation.town.town is not null and incarnation.town.town.aliveCitizen %}
                                    <span>
                                        <img src="{{asset('build/images/small_new.gif')}}" />
                                        <div class="tooltip">
                                            {{ 'Es sind in dieser Stadt noch ein paar Bürger übrig...'|trans({}, 'soul') }}
                                        </div>
                                    </span>
                                {% endif %}
                            </div>
                            <div class="cell padded rw-2 center town-points bold">
                                +{{incarnation.points}}
                            </div>
                        </div>

                    {% else %}
                        <div class="row">
                            <div class="empty">
                                {{'Es wurde keine Stadt gefunden...'|trans({}, 'global')}}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
    {% block js %}
        {{parent()}}
        <script>
        const add_comment = function(id) {
            let comment = null;
            let valid = false;
            comment = window.prompt("{{ 'Was sagst du dazu?'|trans({},'game')|e('js') }}", "");
            if (comment === null) valid = false;
            else {
                valid = !(comment === "")
            }

            if (!valid) return;

            $.ajax.easySend( '{{ path('soul_add_comment') }}', {id: id, comment: comment},
                function () {
                    $.ajax.load(null, '{{ path('soul_me') }}', true);
                } );
        };

        let buttons = document.querySelectorAll('[x-town-id]');
        for (let i = 0; i < buttons.length; i++)
            buttons[i].addEventListener('click', function(e) { e.preventDefault(); e.stopPropagation(); add_comment( this.getAttribute('x-town-id') ); })
        </script>
        {% endblock %}

templates/ajax/soul/shell.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block menu_text %}
    {{ parent() }}
{% endblock %}
{% block ajax %}
    <div class="row soul">
        <div class="cell padded header rw-10 ro-1 rw-md-12 ro-md-0">
            <div class="row tabs">
                <div class="cell-small rw-8 rw-lg-24">
                    {% if app.user.avatar %}
                        <div class="avatar small"><img alt="" src="{{ path('app_web_avatar', {'uid': app.user.id, 'name': app.user.avatar.smallName, 'ext': app.user.avatar.format}) }}"></div>
                    {% endif %}
                    <h4 class="soul-name">
                        <img src="{{ asset('build/images/small_ghost_red.gif') }}" alt="{{'Held'|trans({}, 'game')}}" /> {{ app.user.username }}
                    </h4>
                </div>
                <div class="cell-small rw-3 rw-lg-5 tab{% if soul_tab == "soul_me" %} selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('soul_me') }}">{% trans from 'soul' %}Seele{% endtrans %}</div>
                </div>
                <div class="cell-small rw-3 rw-lg-5 tab{% if soul_tab == "soul_rps" %} selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('soul_rps') }}"><img src="{{ asset('build/images/small_rp.gif') }}" /> {% trans from 'soul' %}Schriften{% endtrans %}</div>
                </div>
                <div class="cell-small rw-3 rw-lg-5 tab{% if soul_tab == "soul_news" %} selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('soul_news') }}"><img src="{{ asset('build/images/small_world.gif') }}" /> {% trans from 'soul' %}News{% endtrans %}</div>
                </div>
                <div class="cell-small rw-3 rw-lg-5 tab{% if soul_tab == "soul_settings" %} selected{% endif %}">
                    <div class="tab-link" x-ajax-href="{{ path('soul_settings') }}">{% trans from 'soul' %}Einstellungen{% endtrans %}</div>
                </div>
                <div class="cell rw-2 tab">
                    <a class="tab-link" target="_self" href="{{ path('auto_logout') }}"><img src="{{ asset('build/images/small_exit.gif') }}" /> {% trans from 'soul' %}Logout{% endtrans %}</a>
                </div>
            </div>
            {% block soul_content %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

templates/ajax/soul/view_town.html.twig
{% extends "ajax/soul/shell.html.twig" %}
{% block soul_content %}
    <div class="row">
        <div class="cell padded rw-4">
            <button class='inline' x-ajax-href="{{path('soul_me')}}"><img src="{{asset('build/images/soul/small_back.gif')}}" alt ="" /> {{'Zurück'|trans({}, 'global')}}</button>
        </div>
    </div>
    <div class="view-town">
        <h5>{{town.name}}</h5>
        <div class="row-table citizens-list">
            <div class="row header">
                <div class="padded cell rw-2">{{'Überlebte Tage'|trans({}, 'soul')}}</div>
                <div class="padded cell rw-1">{{'Ergebnis'|trans({}, 'soul')}}</div>
                <div class="padded cell rw-2">{{'Bürger'|trans({}, 'soul')}}</div>
                <div class="padded cell rw-4">{{'Todesursache'|trans({}, 'soul')}}</div>
                <div class="padded cell rw-3">{{'Kommentar'|trans({}, 'soul')}}</div>
            </div>
            {% for citizen in town.citizens|filter(c => c.end is not null)|sort((a,b) => b.day <=> a.day) %}
                {% set days = citizen.day %}
                {% set sp = days * ( days + 1 ) / 2 %}
            <div class="row">
                <div class="padded cell rw-2">{{citizen.day}}</div>
                <div class="padded cell rw-1 town-points bold">+{{sp}}</div>
                <div class="padded cell rw-2"><span class="link" x-ajax-href="{{ path('soul_visit', {id: citizen.user.id}) }}">{{citizen.user.username}}</span></div>
                <div class="padded cell rw-4">
                    {{citizen.cod.label|trans({}, 'game')}}
                    {% if not citizen.lastWords is empty %}
                    <img src="{{asset('build/images/log/chat.gif')}}" />
                    {% endif %}
                    <div class="tooltip">
                        {% if citizen.lastWords is empty %}
                            <span>{{ 'Dieser Bürger hat keine letzten Worte hinterlassen ...'|trans({}, 'game') }}</span>
                        {% else %}
                            <b>{{"Letzte Worte:"|trans({}, 'game')}}</b> {{ citizen.lastWords }}
                        {% endif %}
                    </div>
                </div>
                <div class="padded cell rw-3 comment">{{citizen.comment}}</div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/ajax/soul/view_town_foreign.html.twig
{% extends "ajax/ajax.html.twig" %}
{% block ajax %}
    {# @var town \App\Entity\TownRankingProxy #}
    <div class="row soul">
        <div class="cell padded header rw-10 ro-1 rw-md-12 ro-md-0">
            <div class="row">
                <div class="cell padded rw-4">
                    <button class='inline' x-ajax-href="{{path('soul_visit', {id: user.id})}}"><img src="{{asset('build/images/soul/small_back.gif')}}" alt ="" /> {{'Zurück'|trans({}, 'global')}}</button>
                </div>
            </div>
            <div class="view-town">
                <h5>{{town.name}}</h5>
                <div class="row-table citizens-list">
                    <div class="row header">
                        <div class="padded cell rw-2">{{'Überlebte Tage'|trans({}, 'soul')}}</div>
                        <div class="padded cell rw-1">{{'Ergebnis'|trans({}, 'soul')}}</div>
                        <div class="padded cell rw-2">{{'Bürger'|trans({}, 'soul')}}</div>
                        <div class="padded cell rw-4">{{'Todesursache'|trans({}, 'soul')}}</div>
                        <div class="padded cell rw-3">{{'Kommentar'|trans({}, 'soul')}}</div>
                    </div>

                    {% for citizen in town.citizens|filter(c => c.end is not null)|sort((a,b) => b.day <=> a.day) %}
                        {# @var citizen \App\Entity\CitizenRankingProxy #}
                        <div class="row">
                            <div class="padded cell rw-2">{{citizen.day}}</div>
                            <div class="padded cell rw-1 town-points bold">+{{citizen.points}}</div>
                            <div class="padded cell rw-2"><span class="link" x-ajax-href="{{ path('soul_visit', {id: citizen.user.id}) }}">{{citizen.user.username}}</span></div>
                            <div class="padded cell rw-4">
                                {{citizen.cod.label|trans({}, 'game')}}
                                {% if not citizen.lastWords is empty %}
                                    <img alt="" src="{{asset('build/images/log/chat.gif')}}" />
                                {% endif %}
                                <div class="tooltip">
                                    {% if citizen.lastWords is empty %}
                                        <span>{{ 'Dieser Bürger hat keine letzten Worte hinterlassen ...'|trans({}, 'game') }}</span>
                                    {% else %}
                                        <b>{{"Letzte Worte:"|trans({}, 'game')}}</b> {{ citizen.lastWords }}
                                    {% endif %}
                                </div>
                            </div>
                            <div class="padded cell rw-3 comment">{{citizen.comment}}</div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}